// Source register — K 锚点表（来源 + 日期取自报告各章引用清单）
// 第三轮重构：按来源类型分组（grp），学术论文以 IEEE 引用格式著录（cite 字段）。
// K 编号保持向后兼容——正文钻取卡 [K#] 引用不受影响。
// grp: paper=学术论文 / vendor=厂商官方文档与博客 / model=模型卡与代码仓库 / third=第三方评测与独立分析 / other=其他
// cat（证据分级徽标）: company=厂商一手 / industry=学术与官方 / broker=第三方评测媒体 / kimi=调研汇编
window.SRC = [
  // ── 学术论文（arXiv / 会议论文）──
  { id: "K2",  grp: "paper", cat: "industry", date: "2025-04", cite: "W. Hackett, L. Birch, S. Trawicki, N. Suri, and P. Garraghan, “Bypassing prompt injection and jailbreak detection in LLM guardrails,” arXiv preprint arXiv:2504.11168, 2025.", fact: "Emoji Smuggling 对 6 个护栏（含 Azure Prompt Shield）注入与越狱均 100% ASR；Unicode Tags 90.15%/81.79%", url: "https://arxiv.org/html/2504.11168v1" },
  { id: "K3",  grp: "paper", cat: "industry", date: "2025-10", cite: "M. Nasr, N. Carlini, et al., “The attacker moves second: Stronger adaptive attacks bypass defenses against LLM jailbreaks and prompt injections,” arXiv preprint arXiv:2510.09023, 2025.", fact: "12 种已发表检测/训练类防御被自适应攻击全部以 >90% 成功率绕过；唯一部分例外是 CaMeL 式架构隔离", url: "https://arxiv.org/abs/2510.09023" },
  { id: "K5",  grp: "paper", cat: "industry", date: "2025-04-12", cite: "D. Jacob, H. Alzahrani, Z. Hu, B. Alomair, and D. Wagner, “PromptShield: Deployable detection for prompt injection attacks,” arXiv preprint arXiv:2501.15145, 2025.", fact: "TPR@0.1%FPR：DeBERTa 级小模型 0–12% vs 8B 级 71.45%（AUC 0.997）；ProtectAI v2 TPR@1%FPR 仅 1.7%", url: "https://arxiv.org/html/2501.15145v2" },
  { id: "K8",  grp: "paper", cat: "industry", date: "2026-05-21", cite: "“Evaluating prompt injection defenses for educational LLM tutors: Security-usability-latency trade-offs,” arXiv preprint arXiv:2605.06669, 2026.", fact: "NeMo self-check 平衡档 0% 绕过率但误报 16.22%、延迟 ≈1.5s；极端 4–5 条 LLM rail 可加 5–10s", url: "https://arxiv.org/html/2605.06669v2" },
  { id: "K11", grp: "paper", cat: "industry", date: "2025-05-20", cite: "S. Palit and D. Woods, “Evaluating the efficacy of LLM safety solutions: The Palit benchmark dataset,” arXiv preprint arXiv:2505.13028, 2025.", fact: "第三方学术评测：Lakera 无上下文场景 recall 0.501、Deepset 数据集 recall 0.707 / FPR 0.007 —— 高精确率、低误报取向，约三到五成攻击漏检", url: "https://arxiv.org/html/2505.13028v2" },
  { id: "K12", grp: "paper", cat: "industry", date: "2023-07 (NeurIPS 2023)", cite: "A. Wei, N. Haghtalab, and J. Steinhardt, “Jailbroken: How does LLM safety training fail?” in Proc. Adv. Neural Inf. Process. Syst. (NeurIPS), 2023.", fact: "两条根本失效机制：目标竞争（competing objectives）与泛化错配（mismatched generalization）", url: "https://arxiv.org/pdf/2307.02483" },
  { id: "K13", grp: "paper", cat: "industry", date: "2024-04", cite: "M. Russinovich, A. Salem, and R. Eldan, “Great, now write an article about that: The crescendo multi-turn LLM jailbreak attack,” arXiv preprint arXiv:2404.01833, 2024.", fact: "多轮渐进越狱：提示中不含对抗文本，5 轮内完成；对 GPT-4 二元成功率 98%、Gemini Pro 100%", url: "https://arxiv.org/abs/2404.01833" },
  { id: "K14", grp: "paper", cat: "industry", date: "2024 (Microsoft Research)", cite: "K. Hines, G. Lopez, M. Hall, F. Zarfati, Y. Zunger, and E. Kiciman, “Defending against indirect prompt injection attacks with spotlighting,” arXiv preprint arXiv:2403.14720, 2024.", fact: "datamarking/encoding 将间接注入 ASR 从 >50% 降到 <2%，零额外模型调用", url: "https://arxiv.org/abs/2403.14720" },
  { id: "K15", grp: "paper", cat: "industry", date: "2025-06", cite: "S. Abdelnabi et al., “LLMail-Inject: A dataset from a realistic adaptive prompt injection challenge,” arXiv preprint arXiv:2506.09956, 2025.", fact: "839 名参与者、去重后 208,095 条唯一自适应攻击；端到端成功率仅 0.8%/0.3%；'首次成功所需尝试数'比静态 ASR 更反映鲁棒性", url: "https://arxiv.org/html/2506.09956v1" },
  { id: "K16", grp: "paper", cat: "industry", date: "2025-03", cite: "E. Debenedetti et al., “Defeating prompt injections by design (CaMeL),” arXiv preprint arXiv:2503.18813, 2025.", fact: "AgentDojo 上 GPT-4o 成功攻击数 233→0；任务解决率 84%→77%（utility −7pp）；原文口径 67% 任务可证安全", url: "https://arxiv.org/abs/2503.18813" },
  { id: "K17", grp: "paper", cat: "industry", date: "2025-06-23", cite: "S. Gakh and M. Bahsi, “Enhancing security in LLM applications: A performance evaluation of early detection systems,” arXiv preprint arXiv:2506.19109, 2025.", fact: "Vigil YARA 对 prompt leak recall 0.248、Rebuff 启发式约 0.33；默认 canary 检查对所有泄露攻击检测率为 0，加显式处理指令后有效", url: "https://arxiv.org/html/2506.19109v1" },
  { id: "K21", grp: "paper", cat: "industry", date: "2026-04-04", cite: "“A systematic empirical study of prompt injection attack effectiveness against large language models (AttackEval-250 / GuardChain),” arXiv preprint arXiv:2604.03598, 2026.", fact: "三级管道：正则 <0.2ms → CPU 分类器 3–50ms（$0.17–2.77/百万请求）→ GPU 模型 24.3ms（$6.80/百万）；仅 ~2% 分布内流量升级到 GPU 级", url: "https://arxiv.org/html/2604.03598v1" },
  { id: "K22", grp: "paper", cat: "industry", date: "2025-04-29", cite: "S. Chennabasappa et al., “LlamaFirewall: An open source guardrail system,” arXiv preprint arXiv:2505.03574, 2025.", fact: "PromptGuard 2（<20ms 每请求必过）+ AlignmentCheck（思维链审计，召回 >80%·FPR <4%）+ CodeShield 三层纵深，Meta 生产使用", url: "https://arxiv.org/abs/2505.03574" },
  { id: "K23", grp: "paper", cat: "industry", date: "2026-06-17", cite: "“Understanding and mitigating prompt leaking attacks in real-world LLM-based applications (AREA),” arXiv preprint arXiv:2606.18673, 2026.", fact: "6 大商业平台 1200 应用实测：>80% 部署在真实对抗查询下泄露系统提示，常连带泄露 API key；机理为 attention drift", url: "https://arxiv.org/html/2606.18673v1" },
  { id: "K26", grp: "paper", cat: "industry", date: "2023-11", cite: "Y. Li et al., “DeepInception: Hypnotize large language model to be jailbreaker,” arXiv preprint arXiv:2311.03191, 2023.", fact: "多层虚拟嵌套场景让有害内容'由虚构角色说出'，可绕过 LlamaGuard 与 OpenAI 检测 API", url: "https://arxiv.org/abs/2311.03191" },
  { id: "K27", grp: "paper", cat: "industry", date: "2025-10", cite: "Shen et al., “A taxonomy-driven approach to jailbreak detection (HackAPrompt),” arXiv preprint arXiv:2510.13893, 2025.", fact: "DAN 类提示总成功率 31.8%；Role Play 出现 331 次为组合攻击最高频成分；prefix injection 单项成功率 31.1%", url: "https://arxiv.org/html/2510.13893v1" },
  { id: "K28", grp: "paper", cat: "industry", date: "2024-09", cite: "A. Wan et al., “CyberSecEval 3: Towards a comprehensive evaluation of cybersecurity risks and capabilities of large language models,” arXiv preprint arXiv:2408.01605, 2024.", fact: "多语言注入集（英文越狱集机翻 15 种语言含中文，TPR/FPR/AUC）；promptfoo 已内置插件，支持 language: ['zh']", url: "https://arxiv.org/html/2408.01605v2" },
  { id: "K31", grp: "paper", cat: "industry", date: "2026-01-22", cite: "Lin et al., “YuFeng-XGuard: A reasoning-centric, interpretable, and flexible guardrail model,” arXiv preprint arXiv:2601.15588, 2026.", fact: "蚂蚁 8B 满血 + 0.6B 蒸馏；Dynamic Policy 推理时动态调整风险类目，动态政策基准 F1=0.91 超 gpt-oss-safeguard-20B 的 0.77", url: "https://arxiv.org/abs/2601.15588" },
  { id: "K32", grp: "paper", cat: "industry", date: "2026-06-11", cite: "Shen et al., “FreoStream: Enhancing stream guardrails via future-aware reasoning and safety-aligned optimization,” arXiv preprint arXiv:2606.13737, 2026.", fact: "Qwen3Guard-Stream-8B 平均 ASR 17.88%→7.90%、ORR 16.73%→6.92%；流式 token 级检测成为可部署组件", url: "https://arxiv.org/abs/2606.13737" },
  { id: "K34", grp: "paper", cat: "industry", date: "2024-07-31", cite: "W. Zeng et al., “ShieldGemma: Generative AI content moderation based on Gemma,” arXiv preprint arXiv:2407.21772, 2024.", fact: "Gemma 2 SFT 内容安全分类器 2B/9B/27B：固定 4 类内容危害、无注入/越狱类；仅英语训练；8K 上下文；Yes/No token softmax 概率", url: "https://arxiv.org/abs/2407.21772" },
  { id: "K35", grp: "paper", cat: "industry", date: "2026-01-26", cite: "D. Liu et al., “AgentDoG: A diagnostic guardrail framework for AI agent safety and security,” arXiv preprint arXiv:2601.18491, 2026.", fact: "轨迹级诊断护栏：输入完整 action–observation 轨迹+工具描述，输出轨迹级判定+三维诊断（风险来源×失败模式×后果）；4B/7B/8B 开源；配套 ATBench", url: "https://arxiv.org/abs/2601.18491" },
  { id: "K36", grp: "paper", cat: "industry", date: "2026-05-28", cite: "“A lightweight and scalable alignment framework for AI agent safety and security (AgentDoG 1.5),” arXiv preprint arXiv:2605.29801, 2026.", fact: "0.8B–8B 四档、约 1k 条影响函数净化样本；R-Judge 92.2% acc / ATBench 72.4%；Pre-Reply 在线护栏：ClawSafety ASR 56.25%→18.75%、AgentHazard 41.92%→26.92%、CIK-Bench 94.29%→42.86%，TTFT 亚秒级", url: "https://arxiv.org/html/2605.29801v1" },
  { id: "K38", grp: "paper", cat: "industry", date: "2026-01", cite: "Kim et al., “Defensive M2S: Training guardrail models on compressed multi-turn conversations,” arXiv preprint arXiv:2601.00454, 2026.", fact: "多轮压缩成伪单轮再分类：Qwen3Guard+hyphenize 93.8% 攻击检测召回（+38.9pp），推理 token 3,231→173（−94.6%），训练成本降 93 倍", url: "https://arxiv.org/html/2601.00454v1" },
  { id: "K39", grp: "paper", cat: "industry", date: "2025-04", cite: "Rahman et al., “X-Teaming: Multi-turn jailbreaks and defenses with adaptive multi-agents,” arXiv preprint arXiv:2504.13203, 2025.", fact: "四智能体自适应多轮攻击：HarmBench ASR 最高 98.1%，加大配置对 GPT-4o/Llama-3/DeepSeek-V3 达 100%，对 Claude 3.7 Sonnet 96.2%", url: "https://www.arxiv.org/pdf/2504.13203v1" },
  { id: "K40", grp: "paper", cat: "industry", date: "2025-03", cite: "Ha et al., “M2S: Multi-turn to single-turn jailbreak,” in Proc. Annu. Meeting Assoc. Comput. Linguistics (ACL), 2025.", fact: "多轮攻击可压缩成单条结构化提示（hyphenize/numberize/pythonize），ASR 70.6–95.9%，甚至超原多轮攻击最多 17.5pp——攻防同构", url: "https://arxiv.org/abs/2503.04856" },
  { id: "K41", grp: "paper", cat: "industry", date: "2025-10-01", cite: "Gong et al., “WAInjectBench: Benchmarking prompt injection detection for web agents,” arXiv preprint arXiv:2510.01354, 2025.", fact: "Web Agent 注入检测基准：对无显式指令/不可察觉扰动的隐式攻击，几乎所有检测器 TPR≈0；文本侧 PromptArmor、DataSentinel 最强", url: "https://arxiv.org/abs/2510.01354" },
  { id: "K42", grp: "paper", cat: "industry", date: "2026-04 ~ 2026-05", cite: "“ClawSafety,” arXiv preprint arXiv:2604.01438, 2026；同组基准：AgentHazard · OS-BLIND · LITMUS（编号见条目说明）.", fact: "Agent 安全基准群：ClawSafety（2604.01438）：skill 文件通道 ASR 69.4% 最危险；AgentHazard：Claude Code ASR 73.63%；OS-BLIND：多 Agent ASR 92.7%；LITMUS：'执行幻觉'，Claude Sonnet 4.6 执行 40.6% 高危操作", url: "https://arxiv.org/html/2604.01438v1" },
  { id: "K43", grp: "paper", cat: "industry", date: "2026-05-22", cite: "“What the guardrail inspects is not what the model infers,” arXiv preprint arXiv:2605.23196, 2026.", fact: "把'护栏 512 窗口 vs 下游 LLM 400K 窗口'的缝隙做成系统攻击（controlled-release prompting）；窗口外内容无人检查", url: "https://arxiv.org/html/2605.23196" },
  { id: "K44", grp: "paper", cat: "industry", date: "2025-06-05", cite: "“Sentinel: SOTA model to protect against prompt injections,” arXiv preprint arXiv:2506.05446, 2025.", fact: "ModernBERT-large 底座原生 8,192 token，内部测试 F1 0.980（ProtectAI v2 为 0.728）；但 >512 长度注入指标未公开，第三方部署仍按 512 截断", url: "https://arxiv.org/html/2506.05446v1" },
  // ── 第四轮新增：学术脉络（sup6）与训练数据（sup7）──
  { id: "K48", grp: "paper", cat: "industry", date: "2025-04", cite: "“DataSentinel: A game-theoretic detection of prompt injection attacks,” arXiv preprint arXiv:2504.11358, 2025.", fact: "博弈论 min-max 训练注入检测器：与自适应攻击者在训练循环里互相博弈，对'针对检测器定制'的注入保持鲁棒；SecAlign/StruQ/IH 三篇最强检测侧被引（137 引）", url: "https://arxiv.org/abs/2504.11358" },
  { id: "K49", grp: "paper", cat: "industry", date: "2025-04", cite: "“Progent: Securing AI agents with privilege control,” arXiv preprint arXiv:2504.11703, 2025.", fact: "最小权限策略控制 agent 工具调用：每个动作只拿完成任务所需最小特权，间接注入成功也无法越权（79 引）", url: "https://arxiv.org/abs/2504.11703" },
  { id: "K50", grp: "paper", cat: "industry", date: "2025-07", cite: "“Defending against prompt injection with a few DefensiveTokens,” arXiv preprint arXiv:2507.07974, 2025.", fact: "输入前插入少量训练好的'防御 token'即达接近 SecAlign 的防注入效果且效用损失更小；部署成本几乎为零（42 引）", url: "https://arxiv.org/abs/2507.07974" },
  { id: "K51", grp: "paper", cat: "industry", date: "2026-03", cite: "“AttriGuard: Defeating indirect prompt injection via causal attribution of tool invocations,” arXiv preprint arXiv:2603.10749, 2026.", fact: "不做输入级语义判别，改对工具调用做因果归因——判断动作由用户指令因果导致还是被不可信数据驱动；直接以 LlamaFirewall 为对比基线", url: "https://arxiv.org/abs/2603.10749" },
  { id: "K52", grp: "paper", cat: "industry", date: "2026-07", cite: "“HaloGuard 1.0: Open weights constitutional classifier for multilingual AI safety,” arXiv preprint arXiv:2607.02079, 2026.", fact: "开源复现 Anthropic Constitutional Classifier 路线，约 1/10 参数量达多语言安全分类 SOTA；引 WildGuard 作多语言基线", url: "https://arxiv.org/abs/2607.02079" },
  { id: "K53", grp: "paper", cat: "industry", date: "2026-02", cite: "“Skill-Inject: Measuring agent vulnerability to skill file attacks,” arXiv preprint arXiv:2602.20156, 2026.", fact: "首个系统测量'Agent Skill 文件注入'的基准（55 引），以 CaMeL/FIDES/Spotlighting 为防御对照——评估 Skill 加载链路的首选基准", url: "https://arxiv.org/abs/2602.20156" },
  { id: "K54", grp: "paper", cat: "industry", date: "2026-01", cite: "“CaMeLs can use computers too,” arXiv preprint arXiv:2601.09923, 2026.", fact: "把 CaMeL 能力+策略架构隔离移植到 Computer-Use Agent，并按 Attacker Moves Second 自适应攻击协议验证仍成立", url: "https://arxiv.org/abs/2601.09923" },
  { id: "K55", grp: "paper", cat: "industry", date: "2025-11", cite: "“BrowseSafe: Understanding and preventing prompt injection within AI browser agents,” arXiv preprint arXiv:2511.20597, 2025.", fact: "Perplexity：浏览器 agent 注入威胁建模与防御基准，评测含 FIDES 式防御；浏览器是间接注入最高发场景", url: "https://arxiv.org/abs/2511.20597" },
  { id: "K56", grp: "paper", cat: "industry", date: "2026-01", cite: "“Defenses against prompt attacks learn surface heuristics,” arXiv preprint arXiv:2601.07185, 2026.", fact: "打脸作：现有注入防御学到的是表面启发式（关键词、格式特征）而非语义理解，分布稍偏即失效——对整条'训练分类器防注入'路线的根本质疑", url: "https://arxiv.org/abs/2601.07185" },
  { id: "K57", grp: "paper", cat: "industry", date: "2025-10", cite: "“Indirect prompt injections: Are firewalls all you need, or stronger benchmarks?” arXiv preprint arXiv:2510.05244, 2025.", fact: "打脸作：简单 agent-tool 接口防火墙在现有基准上能做到'完美'分数——不是防御够好，是基准太弱", url: "https://arxiv.org/abs/2510.05244" },
  { id: "K58", grp: "paper", cat: "industry", date: "2026-03", cite: "“PISmith: RL-based red teaming for prompt injection defenses,” arXiv preprint arXiv:2603.13026, 2026.", fact: "用 RL 红队自动生成绕过注入防御的自适应攻击——把 Attacker Moves Second 的手工精神自动化", url: "https://arxiv.org/abs/2603.13026" },
  { id: "K59", grp: "paper", cat: "industry", date: "2025-03", cite: "“ASIDE: Architectural separation of instructions and data,” arXiv preprint arXiv:2503.10566, 2025.", fact: "模型架构层面用独立嵌入分离指令与数据表示——Spotlighting'输入侧标记'的架构化平行路线", url: "https://arxiv.org/abs/2503.10566" },
  { id: "K60", grp: "paper", cat: "industry", date: "2025-02", cite: "“Can indirect prompt injection attacks be detected and removed?” arXiv preprint arXiv:2502.16580, 2025.", fact: "系统研究间接注入'检测+移除'双任务的可行性边界（65 引）", url: "https://arxiv.org/abs/2502.16580" },
  { id: "K61", grp: "paper", cat: "industry", date: "2024-06 (NeurIPS 2024)", cite: "S. Han et al., “WildGuard: Open one-stop moderation tools for safety risks, jailbreaks, and refusals of LLMs,” in Proc. Adv. Neural Inf. Process. Syst. (NeurIPS), 2024.", fact: "WildGuardMix 92K（87K train + 5.3K test）四象限数据 CC-BY-4.0 全公开；adversarial-benign 象限压误报，越狱 ASR 79.8%→2.4%", url: "https://arxiv.org/html/2406.18495v3" },
  { id: "K62", grp: "paper", cat: "industry", date: "2023-11 (ICLR 2024)", cite: "S. Toyer et al., “TensorTrust: Defending against prompt injection attacks,” in Proc. Int. Conf. Learn. Representations (ICLR), 2024.", fact: "126K 真人玩家注入攻击数据公开；可商用训练主粮候选", url: "https://arxiv.org/abs/2311.01011" },
  { id: "K63", grp: "paper", cat: "industry", date: "2024-10", cite: "“InjecGuard: Benchmarking and mitigating over-defense in prompt injection guardrail models (NotInject),” arXiv preprint arXiv:2410.22770, 2024.", fact: "触发词捷径实证：现有护栏对含触发词良性句过防准确率 <60%（Prompt Guard 仅 0.88%）；MOF 仅混入 1,000 条纠偏样本即把平均准确率拉到 83.48%", url: "https://arxiv.org/abs/2410.22770" },
  { id: "K64", grp: "paper", cat: "industry", date: "2026-06", cite: "“MLJailDe: Machine-translation-based data augmentation for multilingual jailbreak detection,” arXiv preprint arXiv:2606.11202, 2026.", fact: "MBT-DA 回译扩增 + 功能有效性校验：11 语共 2,232 良性 + 1,239 越狱即把低资源语言 F1 从 22–54% 提到 94–98%", url: "https://arxiv.org/html/2606.11202v1" },
  // ── 第五轮新增：论文精读章（报告第 16 章引用清单）──
  { id: "K68", grp: "paper", cat: "industry", date: "2023-07", cite: "A. Zou, Z. Wang, N. Carlini, et al., “Universal and transferable adversarial attacks on aligned language models (GCG),” arXiv preprint arXiv:2307.15043, 2023.", fact: "贪心坐标梯度优化乱码对抗后缀，对 Vicuna/LLaMA-2 高度有效；低查询预算下迁移版（GCG-T）ASR 仅 4.3–11.2%；困惑度过滤即可高效拦截", url: "https://arxiv.org/abs/2307.15043" },
  { id: "K69", grp: "paper", cat: "industry", date: "2023-10", cite: "P. Chao, A. Robey, E. Dobriban, et al., “Jailbreaking black box large language models in twenty queries (PAIR),” arXiv preprint arXiv:2310.08419, 2023.", fact: "攻击者 LLM 生成+评估 LLM 打分迭代精炼，通常 ≤20 次查询产出语义可读越狱提示；困惑度过滤对此类无效", url: "https://arxiv.org/abs/2310.08419" },
  { id: "K70", grp: "paper", cat: "industry", date: "2023-12 (NeurIPS 2024)", cite: "A. Mehrotra, M. Zampetakis, P. Kassianik, et al., “Tree of attacks: Jailbreaking black-box LLMs automatically (TAP),” in Proc. Adv. Neural Inf. Process. Syst. (NeurIPS), 2024.", fact: "PAIR 扩展为树搜索+评估器剪枝；对 GPT-4 Turbo/GPT-4o ASR 超 80%，可绕过 LlamaGuard 等外围检测器", url: "https://arxiv.org/abs/2312.02119" },
  { id: "K71", grp: "paper", cat: "industry", date: "2024-10", cite: "X. Liu, P. Li, E. Suh, et al., “AutoDAN-Turbo: A lifelong agent for strategy self-exploration to jailbreak LLMs,” arXiv preprint arXiv:2410.05295, 2024.", fact: "终身学习 agent 自主探索并结构化复用越狱策略库；低查询预算下 ASR 全面领先 GCG-T/PAIR/TAP，平均每案仅约 6.72 次查询", url: "https://arxiv.org/html/2410.05295v4" },
  { id: "K72", grp: "paper", cat: "industry", date: "2024 (CCS 2024)", cite: "B. Hui, H. Yuan, N. Z. Gong, et al., “PLeak: Prompt leaking attacks against large language model applications,” in Proc. ACM SIGSAC Conf. Comput. Commun. Secur. (CCS), 2024.", fact: "提示泄露形式化为优化问题：增量搜索+多轮响应聚合；对 Poe 平台真实应用重建 68% 系统提示（手工 20%、改造越狱 18%）", url: "https://chatpaper.com/ja/paper/20579" },
  { id: "K73", grp: "paper", cat: "industry", date: "2025-01-30", cite: "Y. Liu, H. Gao, S. Zhai, B. Hooi, et al., “GuardReasoner: Towards reasoning-based LLM safeguards,” arXiv preprint arXiv:2501.18492, 2025.", fact: "R1 式推理引入护栏：GuardReasonerTrain 127K 样本/460K 推理步 + HS-DPO；8B 版 13 基准平均 F1 84.09%，超 GPT-4o+CoT 5.74pp", url: "https://arxiv.org/abs/2501.18492" },
  { id: "K74", grp: "paper", cat: "industry", date: "2025-07-21", cite: "“PromptArmor,” arXiv preprint arXiv:2507.15219, 2025.", fact: "不训练模型，GPT-4o/GPT-4.1/o4-mini 提示化检测+移除：AgentDojo FPR/FNR 均 <1%；但 RTC-Bench 隐式注入检出仅 2–30% [K82]", url: "https://arxiv.org/abs/2507.15219" },
  { id: "K75", grp: "paper", cat: "industry", date: "2024-09-29", cite: "“GenTel-Safe: A unified benchmark and shielding framework for defending against prompt injection attacks,” arXiv preprint arXiv:2409.19521, 2024.", fact: "GenTel-Bench 84,812 条攻击样本、3 大类 28 场景；GenTel-Shield（多语言 E5 embedding 检索管线）越狱防御 97.63%/F1 97.69%", url: "https://arxiv.org/abs/2409.19521" },
  { id: "K76", grp: "paper", cat: "industry", date: "2024-02 (USENIX Security 2025)", cite: "S. Chen et al., “StruQ: Defending against prompt injection with structured queries,” in Proc. USENIX Secur. Symp., 2025.", fact: "结构化查询通道分离（保留 token 分隔 prompt/data + 结构化指令微调）；对 optimization-free 攻击近 0 ASR，但 GCG 优化攻击 ASR 达 56%", url: "https://arxiv.org/abs/2402.06363" },
  { id: "K77", grp: "paper", cat: "industry", date: "2024-10 (CCS 2025)", cite: "S. Chen et al., “SecAlign: Defending against prompt injection with preference optimization,” in Proc. ACM SIGSAC Conf. Comput. Commun. Secur. (CCS), 2025.", fact: "DPO 偏好优化防注入：optimization-free 攻击 0% ASR，GCG/AdvPrompter/NeuralExec 优化攻击 ASR 主要 <10%；utility 波动 <1.5%", url: "https://arxiv.org/html/2410.05451v3" },
  { id: "K78", grp: "paper", cat: "industry", date: "2024-04", cite: "E. Wallace et al., “The instruction hierarchy: Training LLMs to prioritize privileged instructions,” arXiv preprint arXiv:2404.13208, 2024.", fact: "system>developer>user>tool 指令优先级训练；OpenAI 评测直接注入成功率约降 30%；已产品化为 Model Spec chain of command", url: "https://arxiv.org/abs/2404.13208" },
  { id: "K79", grp: "paper", cat: "industry", date: "2025-05-29", cite: "P. Costa et al., “Securing AI agents with information-flow control (FIDES),” arXiv preprint arXiv:2505.23643, 2025.", fact: "把 CaMeL 式架构隔离形式化为信息流控制（IFC）：机密性/完整性标签 + 确定性策略执行 + 选择性信息隐藏；AgentDojo 上保有安全保证完成广泛任务", url: "https://arxiv.org/abs/2505.23643" },
  { id: "K80", grp: "paper", cat: "industry", date: "2025-02-07 (ICML 2025)", cite: "K. Zhu et al., “MELON: Provable defense against indirect prompt injection attacks in AI agents,” in Proc. Int. Conf. Mach. Learn. (ICML), 2025.", fact: "掩码重执行检测：攻击成功时动作更依赖恶意任务；MELON-Aug 在 GPT-4o 上 ASR 0.32%、utility 86.72%，优于五种 SOTA", url: "https://arxiv.org/abs/2502.05174" },
  { id: "K81", grp: "paper", cat: "industry", date: "2024-12", cite: "“Token Highlighter: Inspecting and mitigating jailbreak prompts for LLMs,” arXiv preprint arXiv:2412.18171, 2024.", fact: "GCG/PAIR/TAP/AutoDAN 机制综述与缓解（精读章攻击组方法机制的对照来源）", url: "https://arxiv.org/pdf/2412.18171" },
  { id: "K82", grp: "paper", cat: "industry", date: "2025-05", cite: "“RTC-Bench: Realistic adversarial testing of computer-use agents,” arXiv preprint arXiv:2505.21936, 2025.", fact: "计算机使用（CUA）场景隐式注入实测：PromptArmor 类提示化检测检出率仅 2–30%（附录 G）", url: "https://arxiv.org/html/2505.21936v4" },
  // ── 第六轮新增：SingGuard 双子（sup8，报告 §11.6）──
  { id: "K83", grp: "paper", cat: "industry", date: "2026-06-22 (v3 2026-06-25)", cite: "SingGuard Team, AI Security Lab, Ant Group, “SingGuard: A policy-adaptive multimodal LLM guardrail with dynamic reasoning,” arXiv preprint arXiv:2606.22873, 2026.", fact: "政策自适应多模态护栏（Qwen3-VL 2B/4B/8B）：政策作运行时自然语言输入；官方报告 6 大评测家族 35 个数据集平均 F1 全部第一（厂商自建基准，暂无第三方复测）；政策遵循准确率 0.6465→0.7415", url: "https://arxiv.org/abs/2606.22873" },
  { id: "K84", grp: "paper", cat: "industry", date: "2026-07", cite: "SingGuard Team, AI Security Lab, Ant Group, “SingGuard-NSFA: Agentic behavior guardrails with pluggable per-domain classification heads,” arXiv preprint arXiv:2607.13081, 2026.", fact: "智能体行为护栏（Qwen3.5-Base 0.8–9B）：7 域/28 风险/185 变体；判别头 45–57ms、官方口径 F1>94%（自建基准）；分类头插件增强 Llama Guard 3 多语言 Query F1 67.66→85.23（+17.6）；133 语言基准", url: "https://arxiv.org/abs/2607.13081" },
  // ── 厂商官方文档与技术博客 ──
  { id: "K18", grp: "vendor", cat: "company", date: "2026-01-30", name: "Microsoft Learn", title: "Prompt Shields in Azure AI Content Safety", fact: "userPrompt 直接越狱 + documents[] 间接注入双检测；中英法德西意日葡 8 语言训练测试；每月 5,000 条免费，约 $0.375/1K", url: "https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection" },
  { id: "K29", grp: "vendor", cat: "industry", date: "2025-10", name: "Meta AI Security", title: "Agents Rule of Two", fact: "Agent 同时具备'处理不可信输入、访问敏感数据、可对外通信/改状态'三者之二时必须引入强约束", url: "https://arxiv.org/abs/2510.09023" },
  { id: "K33", grp: "vendor", cat: "company", date: "2025-10-29", name: "OpenAI", title: "gpt-oss-safeguard 技术报告 + 官方博客", fact: "政策推理式护栏：bring-your-own-policy + CoT 判定；120b/20b 两档 Apache 2.0；官方多政策准确率 46.3%/43.6%（超 gpt-5-thinking 43.2%）；官方定位'小分类器预筛 + Safety Reasoner 深检'；自认注入/越狱基准弱于基座", url: "https://openai.com/index/introducing-gpt-oss-safeguard/" },
  { id: "K47", grp: "vendor", cat: "company", date: "2025-10-29", name: "OpenAI Cookbook", title: "User guide for gpt-oss-safeguard", fact: "政策最优 400–600 token；harmony 双通道（analysis 推理链 + final 判定）；支持 Structured Outputs 与 reasoning effort 三档；官方推荐'高召回前置过滤 + safeguard 精审'两段式 hybrid", url: "https://cookbook.openai.com/articles/gpt-oss-safeguard-guide" },
  // ── 模型卡与代码仓库 ──
  { id: "K1",  grp: "model", cat: "company", date: "2024-03 · 测试 2025-05~08", name: "Lakera", title: "PINT Benchmark 官方仓库", fact: "PINT 官方榜：Lakera 95.22 / AWS 89.24 / Azure 89.12 / ProtectAI 79.14 / PromptGuard2 78.76 / Model Armor 70.07；4,314 条输入，含 1,298 条非英文子集", url: "https://github.com/lakeraai/pint-benchmark" },
  { id: "K4",  grp: "model", cat: "company", date: "2025-04-30", name: "Meta", title: "Llama Prompt Guard 2 Model Card", fact: "86M Recall@1%FPR 97.5%、多语言 AUC 0.995、A100 92ms；22M 19.3ms；AgentDojo 86M 81.2% / 22M 78.4% vs ProtectAI 22.2% / deepset 13.5%", url: "https://www.modelscope.cn/models/LLM-Research/Llama-Prompt-Guard-2-86M" },
  { id: "K6",  grp: "model", cat: "company", date: "2025-09-30", name: "Qwen", title: "Qwen3Guard 官方仓库 + 技术报告 (arXiv:2510.14276)", fact: "Gen/Stream 两版各 0.6B/4B/8B，119 万条训练数据、119 种语言，中英文基准 SOTA，Apache-2.0", url: "https://github.com/QwenLM/Qwen3Guard" },
  { id: "K9",  grp: "model", cat: "company", date: "2026-07-01 检索", name: "NVIDIA-NeMo", title: "Guardrails 仓库 + PyPI", fact: "最新版 0.23.0 已移除 beta 免责声明（≤0.15.0 曾明示不建议生产）；Colang 2.0 仍 beta", url: "https://github.com/NVIDIA-NeMo/Guardrails" },
  { id: "K10", grp: "model", cat: "company", date: "2025-05-16 归档", name: "ProtectAI", title: "Rebuff 仓库（已归档）", fact: "2024-01 停更、2025-05 归档；学术横评 FPR 0.68、单 prompt 延迟 29.33s，生产不可用；四层架构思想保留", url: "https://github.com/protectai/rebuff" },
  { id: "K45", grp: "model", cat: "company", date: "2025-04-29", name: "Meta", title: "Llama Guard 4（12B 多模态）模型卡", fact: "从 Llama 4 Scout 剪枝为 dense，单卡 24GB、163,840 token 上下文；输出 safe/unsafe + MLCommons 14 类危害码；较 LG3 多图 recall +20%、英文文本 F1 +8%", url: "https://huggingface.co/meta-llama/Llama-Guard-4-12B" },
  { id: "K46", grp: "model", cat: "company", date: "2025-09 开源 / 2025-10 更新", name: "京东 jd-opensource", title: "JoySafety v2（Apache-2.0）", fact: "生产级开源安全框架：DAG 策略引擎，内置多轮对话上下文注入检测原子能力；v2 审核模型重点加强提示注入、多语种、多轮检测", url: "https://github.com/jd-opensource/JoySafety" },
  { id: "K85", grp: "model", cat: "company", date: "2026-07-13 官宣开源（访问 2026-07-24）", name: "inclusionAI（蚂蚁集团 AI 安全实验室）", title: "SingGuard / SingGuard-NSFA 开源仓库与权重", fact: "代码与权重 Apache-2.0 全量开放（可商用）：GitHub inclusionAI/SingGuard（2026-05-25 创建）与 inclusionAI/SingGuard-NSFA；HF/ModelScope 双平台含 GGUF；NSFA_Benchmarks 基准集已公开，SingGuard-Bench（56,340 条）待发布", url: "https://github.com/inclusionAI/SingGuard" },
  { id: "K65", grp: "model", cat: "company", date: "2024 (NeurIPS 2024)", name: "NVIDIA", title: "Aegis AI Content Safety Dataset 2.0", fact: "34,248 条：12 核心危害类 + 9 细粒度风险；12 名受训标注员 + 3 个 LLM 陪审团多数投票 + 5,000 条合成 refusal；明确以可商用训练为设计目标；34K 条 PEFT 微调 8B 持平 3 倍数据的 WildGuard", url: "https://huggingface.co/datasets/nvidia/Aegis-AI-Content-Safety-Dataset-2.0" },
  { id: "K66", grp: "model", cat: "company", date: "2024", name: "ProtectAI", title: "deberta-v3-base-prompt-injection-v2 模型卡", fact: "训练集内 Accuracy 99.99%，未训练分布的 2 万条外测掉到 95.25%——'训练集内指标虚高'教科书案例；v1 明确 70:30 良性:攻击配比", url: "https://huggingface.co/protectai/deberta-v3-base-prompt-injection-v2" },
  // ── 第三方评测与独立分析 ──
  { id: "K7",  grp: "third", cat: "broker", date: "2026-01-21", name: "CSDN", title: "Qwen3Guard-Gen 0.6B/4B/8B 实测", fact: "A10G 首字延迟 89/167/253ms、显存 3.1/9.8/18.7GB；50 条人工样本准确率 82%/91%/96%（单一来源，置信度中）", url: "https://blog.csdn.net/weixin_29041443/article/details/157189195" },
  { id: "K19", grp: "third", cat: "broker", date: "2025-10-01", name: "General Analysis", title: "GA Guardrail 独立基准", fact: "Azure Prompt Shields acc 0.879；Google Model Armor acc 0.779 / FPR 0.225", url: "https://generalanalysis.com/blog/ga-guard-series" },
  { id: "K20", grp: "third", cat: "broker", date: "2026-05-07", name: "Spheron", title: "NVIDIA NeMo Guardrails 生产部署", fact: "生产栈：PromptGuard2 86M 快闸 → 灰区升级 LlamaGuard 3 8B（INT4 p50 ~20ms、VRAM 4GB）；总输入轨 p50 20ms / p99 50ms", url: "https://www.spheron.network/blog/nemo-guardrails-production-deployment-llm-gpu-cloud/" },
  { id: "K30", grp: "third", cat: "broker", date: "2026-02", name: "sibyllinesoft/clean", title: "AgentDojo APR 对比（独立复测）", fact: "独立复测口径：Prompt Guard 2 86M 81.2% / 22M 78.4% / ProtectAI 22.2% / deepset 13.5%", url: "https://github.com/sibyllinesoft/clean" },
  { id: "K37", grp: "third", cat: "broker", date: "2026-03-02", name: "jdleo/tinysafe-2", title: "ToxicChat 独立排行榜", fact: "gpt-oss-safeguard-20b F1 79.9% / 120b 79.3% 居开源护栏榜首，高于 Qwen3Guard-8B 73%、LlamaGuard3-8B 51%、ShieldGemma 42–67%（27B 仅 48%）", url: "https://github.com/jdleo/tinysafe-2" },
  { id: "K67", grp: "third", cat: "broker", date: "2025-07", name: "Tomoro", title: "gpt-oss-safeguard 发布对信任与安全意味着什么", fact: "10k 人工标注垂直域数据 SFT Qwen3-0.6B，准确率 57% 对 gpt-oss-safeguard-120B 的 15%——垂直域小数据 SFT 可胜超大通用护栏", url: "https://tomoro.ai/insights/what-the-release-of-openai-gpt-oss-safeguard-models-means-for-trust-and-safety" },
  { id: "K86", grp: "third", cat: "broker", date: "2026-07-15", name: "Help Net Security", title: "SingGuard-NSFA: Open-source guardrails for agentic AI", fact: "第三方报道口径：NSFA 0.8B 可对标竞品 8B；9B 泛化 F1 91.29%；50ms 级实时截停定位——注意仍转述官方数据，非独立复测", url: "https://www.helpnetsecurity.com/2026/07/15/singguard-nsfa-open-source-agentic-ai-guardrails/" },
  // ── 其他（聚合 / 社区 / 媒体）──
  { id: "K24", grp: "other", cat: "company", date: "2025", name: "OWASP GenAI Security Project", title: "LLM07 System Prompt Leakage", fact: "缓解第一条：Keep secrets out of prompts —— 提示泄露应被视为必然事件而非可防事件", url: "https://genai.owasp.org/llmrisk/llm07-system-prompt-leakage/" },
  { id: "K25", grp: "other", cat: "company", date: "2025-09-19", name: "IT Pro", title: "Check Point 收购 Lakera", fact: "Check Point 以约 3 亿美元收购 Lakera；新签销售走 Check Point 企业采购渠道，定价与路线图存在不确定性", url: "https://www.itpro.com/business/acquisition/check-point-buys-lakera-to-secure-the-full-enterprise-ai-lifecycle" },
];

// render the grouped K table into #source-list（分组小标题 + 全部/仅论文筛选）
(function () {
  const host = document.getElementById("source-list");
  if (!host) return;
  const catName = { company: "厂商一手", broker: "第三方评测", industry: "学术/官方", kimi: "调研汇编" };
  const GROUPS = [
    { key: "paper", name: "Ⅰ · 学术论文", sub: "arXiv / 会议论文（NeurIPS · ACL 等）· IEEE 格式著录" },
    { key: "vendor", name: "Ⅱ · 厂商官方文档与技术博客", sub: "Microsoft · Meta · OpenAI 官方" },
    { key: "model", name: "Ⅲ · 模型卡与代码仓库", sub: "Hugging Face / GitHub / ModelScope" },
    { key: "third", name: "Ⅳ · 第三方评测与独立分析", sub: "独立基准 · 生产复盘 · 个人复测" },
    { key: "other", name: "Ⅴ · 其他（聚合 / 社区 / 媒体）", sub: "标准组织 · 行业媒体" },
  ];

  // 筛选条
  const bar = document.createElement("div");
  bar.className = "src-filter";
  bar.innerHTML = `<span class="src-filter-label">FILTER</span>
    <button data-f="all" class="on">全部 K1–K${Math.max(...window.SRC.map(s => +s.id.slice(1)))}</button>
    <button data-f="paper">仅学术论文（${window.SRC.filter(s => s.grp === "paper").length} 条）</button>`;
  host.parentNode.insertBefore(bar, host);

  function citeLine(s) {
    if (s.grp === "paper") return s.cite;
    return `${s.name}. ${s.title}. ${s.url}, ${s.date}.`;
  }

  GROUPS.forEach(g => {
    const items = window.SRC.filter(s => s.grp === g.key);
    if (!items.length) return;
    const head = document.createElement("div");
    head.className = "src-grp-head";
    head.dataset.grp = g.key;
    head.innerHTML = `<span class="src-grp-name">${g.name}</span><span class="src-grp-sub">${g.sub} · ${items.length} 条</span>`;
    host.appendChild(head);
    items.forEach(s => {
      const row = document.createElement("div");
      row.className = "src-row";
      row.dataset.grp = s.grp;
      row.innerHTML = `<span class="s-fact"><b>[${s.id}]</b> ${s.fact}</span>
        <span class="s-cite"><span class="src-cat ${s.cat}">${catName[s.cat]}</span>${citeLine(s)} <a href="${s.url}" target="_blank" rel="noopener">链接</a></span>`;
      host.appendChild(row);
    });
  });

  bar.querySelectorAll("button").forEach(b => b.addEventListener("click", () => {
    bar.querySelectorAll("button").forEach(x => x.classList.toggle("on", x === b));
    const f = b.dataset.f;
    host.querySelectorAll(".src-row, .src-grp-head").forEach(el => {
      el.style.display = (f === "all" || el.dataset.grp === f) ? "" : "none";
    });
  }));
})();
